web:
  build: ./images/nginx/1.13.12
  ports:
    - "80:80"
    - "9009:80"
  volumes:
    - /var/www:/var/www
    - ./config/nginx/conf.d:/etc/nginx/conf.d
  links:
    - php
php:
  build: ./images/php/7.1.16
  volumes:    
    - /var/www:/var/www
  links:
    - db
db:
  build: ./images/mysql/5.7
  ports:
   - "3306:3306"
  volumes:
    - /data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: "%"
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test